---
deployment:
  tasks:
    - export FRONTEND_PATH=/home/khaled1976/public_html/
    - export BACKEND_PATH=/home/khaled1976/api.khaledshoes.dz/
    - /bin/cp -R frontend/dist/* $FRONTEND_PATH
    - /bin/cp -R khaled shoes manage.py requirements.txt passenger_wsgi.py $BACKEND_PATH
