# Generated by Django 4.2.30 on 2026-09-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0058_alter_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_b2b',
        ),
        migrations.RemoveField(
            model_name='deliveryrate',
            name='b2b_price_desk',
        ),
        migrations.RemoveField(
            model_name='deliveryrate',
            name='b2b_price_home',
        ),
        migrations.RemoveField(
            model_name='product',
            name='b2b_min_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='b2b_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='b2b_price_box',
        ),
        migrations.RemoveField(
            model_name='product',
            name='b2b_price_carton',
        ),
        migrations.RemoveField(
            model_name='product',
            name='b2b_promo_price_box',
        ),
        migrations.RemoveField(
            model_name='product',
            name='b2b_promo_price_carton',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_b2b',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_b2b_pending',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nrc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nrc_file',
        ),
    ]
