# Generated by Django 4.2.30 on 2026-09-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0059_remove_customer_is_b2b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mylerz_barcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mylerz_pickup_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mylerz_status',
        ),
        migrations.AddField(
            model_name='order',
            name='yalidine_status',
            field=models.CharField(blank=True, max_length=200, verbose_name='Statut Yalidine'),
        ),
        migrations.AddField(
            model_name='order',
            name='yalidine_tracking',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tracking Yalidine'),
        ),
    ]
