# Generated by Django 4.2.30 on 2026-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0063_supplier_purchase_invoice_number_purchase_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Montant à partir duquel la livraison est gratuite', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='Le site est actuellement en maintenance. Veuillez revenir plus tard.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='ID du Pixel Facebook/Meta', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='new_account_discount_enabled',
            field=models.BooleanField(default=False, help_text='Activer la remise pour création de compte'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='new_account_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de remise pour les nouveaux comptes', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tiktok_pixel_id',
            field=models.CharField(blank=True, help_text='ID du Pixel TikTok', max_length=50),
        ),
    ]
